### ISSUE TITLE
useLayoutEffect 和 useEffect 表现一样

### ISSUE THREAD

**Issue by shaodahong** [BetaSu/just-react#15]
https://react.iamkasong.com/renderer/prepare.html#layout%E4%B9%8B%E5%90%8E

演示的 Demo 表现不出来两者的差异

**Comment by BetaSu** [comment]
这里`Demo` 的目的是为了展示`useLayoutEffect`的工作原理，揭示 **在这些回调方法中可能触发新的更新，新的更新会开启新的`render-commit`流程。**这一论点。

如果要对比 `useLayoutEffect`和`useEffect`区别，考虑在`useLayoutEffect`中执行些阻塞线程的工作应该会看到区别。

**Comment by BetaSu** [comment]
不过 你提出的问题确实有代表性， 我会在后续 加上 这两者的对比demo。 感谢反馈

**Comment by shaodahong** [comment]
是的，原理我是知道的，但是 Demo 没有说服力，而且 `useLayoutEffect` 和 `useEffect` 也是经常问的点，结合场景会比较好

**Comment by linsi123** [comment]
useEffect官网说是在浏览器渲染页面后执行的；你这里说是在commit阶段执行

**Comment by BetaSu** [comment]
> useEffect官网说是在浏览器渲染页面后执行的；你这里说是在commit阶段执行

可以去了解下 `commit`阶段做的事情，这两种说法不冲突

**Comment by linsi123** [comment]
为什么reconciler的mount要生成子fibre，而不是生成当前的fibre

**Comment by BetaSu** [comment]
> 为什么reconciler的mount要生成子fibre，而不是生成当前的fibre

书里有讲。

另外，`useLayoutEffect` Demo 更新了，关闭本issue

**Comment by linsi123** [comment]
看不懂，能加你微信吗
