### ISSUE TITLE
rootFiberNode 是不是改成 fiberRootNode 会比较好？

### ISSUE THREAD

**Issue by ParadeTo** [BetaSu/just-react#23]
原因有以下几点：

- 因为是由 `FiberRootNode` 实例化而来

- rootFiberNode 和 rootFiber 意思感觉有点相近，容易混淆

- fiberRootNode 语义更符合，表示 fiber 树的根节点，而 rootFiberNode 则表示根 fiber 节点

- 源码中叫 fiberRoot

如果你觉得需要改的话，我可以贡献一个 PR 😆

**Comment by JunlinZhu-Tommy** [comment]
同意，fiberRootNode更能代表是整个应用的根结点。

**Comment by BetaSu** [comment]
很好的建议，欢迎PR
