### ISSUE TITLE
update数据结构

### ISSUE THREAD

**Issue by blackgoldman** [BetaSu/just-react#33]
极简hooks实现一章中，存在多个update时，update数据结构的queue（环状单向链表）是只保留第一个和最后一个update吗？这样设计是为啥呢？

**Comment by BetaSu** [comment]
需要明确，并不是`update`数据结构的`queue`。 而是`hook`数据结构的`queue`。

`update`保存在`hook.queue`中。

既然是`链表`，那么通过一个就能找到其他所有节点。 所以并不是只保留第一个和最后一个，而是保存一整条链表。
