### ISSUE TITLE
请问：useEffect在commit的layout阶段执行的原因？

### ISSUE THREAD

**Issue by Fhasghrge** [BetaSu/just-react#39]
![image](https://user-images.githubusercontent.com/45527332/94153769-c4a37500-feaf-11ea-9974-1fdc6d10d455.png)
楼主你好：
在layout阶段可以执行useEffect的调用和销毁，一般不是在before mutation执行useEffect的回调，在delete某个节点时执行useEffect执行销毁。
如果在layout执行其调用和销毁，不是清楚了before mutation中执行的回调？
此外我的这个代码在页面渲染完成，也就是layout并没有发现页面的标题发生了改变？
`
useEffect(() => {
        return () => {
            document.title='???'
        }
    }, [])
`
谢谢帮忙解答💕

**Comment by BetaSu** [comment]
这里是**调度**`useEffect`的回调，并不是**调用**他。 调用是在`commit`阶段完成后异步执行的，而执行的回调就来自于**调度**

**Comment by Fhasghrge** [comment]
我理解了，就是对useEffect本身进行回调进行处理
