### ISSUE TITLE
React 新手🥬小白的苦恼

### ISSUE THREAD

**Issue by ShenQingchuan** [BetaSu/just-react#46]
作为一个从 Vue 技术栈转入的同学，我深感 React 社区文化的浓厚（潜台词：TMD 工程环境真难配）
大佬可否出一期文章，教教大家怎么样构建一个更系统、更工程化一点的 React 项目，让大家用起来学起来没那么懵 😭

**Comment by lizy0329** [comment]
cra 不行？
