### ISSUE TITLE
多节点 Diff 的时候， abcd -> acbd 的情况要怎么处理？

### ISSUE THREAD

**Issue by xylin123** [BetaSu/just-react#52]
新 acbd
旧 abcd

按照分析来说，
第一轮遍历 确定 a 可以复用，并在遍历 第二个元素 c 的时候 发现 key 不同，停止了遍历 进入了 第二轮遍历。

此时: 
old bcd
new cbd
开始 第二轮遍历 -> c
lastPlacedIndex = 0
oldIndex = 2
oldIndex >= lastPlacedIndex
不移动且 lastPlacedIndex = oldIndex = 2

-> b
oldIndex = 1
oldIndex < lastPlacedIndex
标记移动 lastPlacedIndex = 2 不变

-> d
oldIndex = 3
oldIndex >= lastPlacedIndex
不移动且 lastPlacedIndex = oldIndex = 3

至此遍历完毕。

只有 b 元素被标记移动， 但是没有说要怎么移动， 移动到最右边吗。
但是实际中，也只有移动到 c 的后面

**Comment by ParadeTo** [comment]
commit 的时候会调用 getHostSibling 得到 b 的 sibling 对应的真实 dom

**Comment by xylin123** [comment]
学习了，我研究下。
